### PR TITLE
Corrected node-express-mongoose.md

### PR DESCRIPTION
**Pull request by Ajeett01**
## Related Issue
- [bug]: correction required in doc quickstart
Closes: keploy/keploy#1581

#### Describe the changes you've made
Changed the node-express-mongo guide.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added
NA

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Ajeett01** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Sonichigo** [comment]
Hey @Ajeett01 build is failing https://github.com/keploy/docs/actions/runs/8187452095/job/22389688273?pr=358

**Comment by Ajeett01** [comment]
> Hey @Ajeett01 build is failing https://github.com/keploy/docs/actions/runs/8187452095/job/22389688273?pr=358

Some of the style tags on the images were not close properly , maybe that was failing the build.
Rest all things seem to be fine.
Please tell if issues exist.

**Review by Sonichigo — APPROVED** [review]
LGTM

**Pull request merged**
