### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by helloausrine**
Hi There,

I hope you're well! I found a small spelling mistake in your README so I went ahead and fixed it for you.

Love the project, keep up the good work!

Kind regards,
HelloAusrine

Signed-off-by: Taylor Richards helloausrine@gmail.com

### CODE REVIEW

**Comment by nehagup** [comment]
Thanks for the correction @helloausrine. Can you please sign the DCO? After that, I shall merge this PR.

**Comment by helloausrine** [comment]
Signed-off-by: Taylor Richards helloausrine@gmail.com

**Comment by nehagup** [comment]
@helloausrine you can sign the DCO by adding the signature locally in the commit message and force pushing. You can click on "Details" of the Failed DCO actions to find the instructions

**Comment by ShivamTyagi12345** [comment]
Hey @helloausrine  Kindly signup the DCO as that happens to be an important requirement , else i shall be closing this PR :100: Thanks

**Pull request merged**
