### PR TITLE
Added FAQs to Keploy/docs website

### PR DESCRIPTION
**Pull request by yaten2302**
# Pull Request Template

## Description

This PR adds FAQ section to the docs website of Keploy.

Fixes https://github.com/keploy/keploy/issues/2095

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Sonichigo** [comment]
@yaten2302 please the actions! build is failing : https://github.com/keploy/docs/actions/runs/10034678131/job/27731088374?pr=428

**Comment by yaten2302** [comment]
@Sonichigo sir, could you please guide that why the build is failing and how can i fix this?

**Comment by yaten2302** [comment]
@Sonichigo sir, I've made the changes, and also, I've rearranged the order of questions - https://github.com/keploy/keploy/pull/2105#pullrequestreview-2191602086, now ig there are no build issues?

**Comment by Swpn0neel** [comment]
Fix the DCO @yaten2302!

**Review by Swpn0neel — APPROVED** [review]

**Comment by Sonichigo** [comment]
> @Swpn0neel sir, fixed the DCO checks 👍

@yaten2302 the build is still failing 

```
  "reason": "Expected a closing tag for `<br>` (151:47-151:51) before the end of `paragraph`",
  "ruleId": "end-tag-mismatch",
  "source": "mdast-util-mdx-jsx"
```

Please refer : - https://github.com/keploy/docs/actions/runs/10056225253/job/27806219617?pr=428

**Comment by yaten2302** [comment]
@Sonichigo sir, actually, I use npm and not yarn, so is it creating problems because of that?

**Comment by Swpn0neel** [comment]
> @Sonichigo sir, actually, I use npm and not yarn, so is it creating problems because of that?

Use <br/> instead of <br>

**Comment by yaten2302** [comment]
@Swpn0neel sir, actually, in all the questions, the tag is same - `<br>`, but then why this error is being shown only on line 151? <br>
image

**Comment by Swpn0neel** [comment]
image
Try that in all the lines!

**Comment by yaten2302** [comment]
@Swpn0neel sir, I've made the changes, could you please review that now the build is working fine?

**Comment by Swpn0neel** [comment]
@Sonichigo Kindly check!

**Review by Sonichigo — APPROVED** [review]
LGTM

**Pull request merged**
