### PR TITLE
Removed background from images, closes #32

### LINKED ISSUE #32: [feature]: Make the images background transparent
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

When we read the documentation and encounter any image explaining the above concept or showing an example, it creates a different impact in light and dark mode. 

For example,
As shown below, the image looks perfect in the light mode.

Light Mode

But, as soon as I toggle to the dark mode, which is opted comparatively more by users, the images look odd and non-appealing.

Dark Mode

Apart from this, 
1. The images could have a better contrast that matches the theme of Keploy. 
2. The image under **Automatically mock Mutations** shows the third-party services. Design an image that shows the logos in a line instead of giving a scattered view.

### Why should this be worked on?

User Experience is important. These changes will help them absorb the content easily.

### PR DESCRIPTION
**Pull request by Guillergood**
# Pull Request Template

## Description

Changed the background of some images to improve the user experience

Fixes #32  (issue)

## How Has This Been Tested?

Just checking in the images to see if they had background or not

## Checklist:

- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have made corresponding changes to the documentation.
- [X] I have added corresponding tests.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Guillergood** [comment]
I was taking a look at the test failure in the [job](https://github.com/keploy/docs/actions/runs/3183566663/jobs/5190937001), it does not seem to be something wrong with the images, though 😄

**Comment by ShivamTyagi12345** [comment]
> I was taking a look at the test failure in the [job](https://github.com/keploy/docs/actions/runs/3183566663/jobs/5190937001), it does not seem to be something wrong with the images, though smile

Thanks for the PR @Guillergood , regarding the test failure - we are working on that as a separate issue and shall resolve it quickly, You may visit the [issue here](https://github.com/keploy/docs/issues/59)

**Review by nehagup — CHANGES_REQUESTED** [review]
The image in static/img/keploy-logo-twitter-card.png needs to be updates since Keploy logo has been changed.

**Comment by Guillergood** [comment]
> The image in static/img/keploy-logo-twitter-card.png needs to be updates since Keploy logo has been changed.
Changes amended 👍🏻

**Pull request merged**
