### PR TITLE
changed port number (8080 , 8081) to 6789

### PR DESCRIPTION
**Pull request by RJ025**
# Pull Request Template

changed port number (8080 , 8081) to 6789

Fixes # 92

documentation change

Please delete options that are not relevant.

- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] I have made corresponding changes to the documentation.

`Signed-off-by: ritik jain <ritikjain025@gmail.com>`

### CODE REVIEW

**Comment by RJ025** [comment]
@nehagup  I have done the mentioned changes please look into it.

**Review by nehagup — APPROVED** [review]
@RJ025 LGTM!  👏Can you please sign the DCO?

**Comment by RJ025** [comment]
> @RJ025 LGTM! 👏Can you please sign the DCO?

could you please help me with it means how can I do it 😅 @nehagup

**Comment by nehagup** [comment]
> > @RJ025 LGTM! 👏Can you please sign the DCO?
> 
> could you please help me with it means how can I do it 😅 @nehagup

@RJ025 you can click on the details of the failing DCO check and you will find the right instructions =.

**Comment by RJ025** [comment]
@nehagup  I added DCO signoff could you please look into it.

**Pull request merged**
