### PR TITLE
docs: added definition for Deduplication Algorithm

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
# Pull Request Template

## Description

Added definition for Deduplication Algorithm in the glossary section of the docs.
Closes [#1125](https://github.com/keploy/keploy/issues/1125)

### CODE REVIEW

**Comment by Shashwat79802** [comment]
Please see for the lint error, make your commit message as- "docs: added definition for deduplication algorithm".
Rest is good.

**Comment by aarishshahmohsin** [comment]
am I supposed to make any other change?

**Comment by aarishshahmohsin** [comment]
I have changed it.

**Review by Sonichigo — APPROVED** [review]
LGTM 🚀

**Review by Shashwat79802 — APPROVED** [review]

**Comment by aarishshahmohsin** [comment]
Is there any problem in the PR because of it not being merged?

**Pull request merged**
