### PR TITLE
[docs]: Added instructions for using npm to run the Docusaurus site locally

### PR DESCRIPTION
**Pull request by GauriBhandari**
# Pull Request Template

## Description

This pull request adds instructions for using npm to run the Docusaurus site locally. This addition will help users who prefer to use npm over yarn, making the documentation more inclusive.

Fixes # (issue)
#2094 (https://github.com/keploy/keploy/issues/2094#event-13560375003)

## Type of change
Documentation Enhancement 

Please delete options that are not relevant.
- [x] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Sonichigo** [comment]
@GauriBhandari one thing can be done here. We did had a plan to migrate to npm package manager in roadmap for the docs repo, as other ui based repo also work with npm. Can you migrate the docs repo from `yarn` to `npm`. 

Things that would be need update are yarn.lock file, workflows, build checks, package*.json and such with guide on how to run it locally.

**Comment by GauriBhandari** [comment]
okay i can , but i didn't get what exactly is needed, could you please elaborate a little ?

**Comment by Sonichigo** [comment]
> okay i can , but i didn't get what exactly is needed, could you please elaborate a little ?

Migration from using `yarn` to `npm` on docs website.

**Comment by GauriBhandari** [comment]
okay i will do it .

**Comment by starvader13** [comment]
> hii @Sonichigo , i am getting this Lint Codebase error , i have tried troubleshooting but still the error persists, could you please help ?

Hey @GauriBhandari, (`Updated documentation to reflect npm migration`) you can resolve the issue by rewording your commits and adding a type to the commit subject. Additionally, for one of your commits (`docs: update npm migration instructions`), you need to either shorten the commit body or break it into points.

Reference: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

**Comment by GauriBhandari** [comment]
> > hii @Sonichigo , i am getting this Lint Codebase error , i have tried troubleshooting but still the error persists, could you please help ?
> 
> Hey @GauriBhandari, (`Updated documentation to reflect npm migration`) you can resolve the issue by rewording your commits and adding a type to the commit subject. Additionally, for one of your commits (`docs: update npm migration instructions`), you need to either shorten the commit body or break it into points.
> 
> Reference: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

okay will do , thankyou

**Review by Sonichigo — COMMENTED** [review]
LGTM! @GauriBhandari the changes will also take place here : - https://github.com/keploy/docs?tab=readme-ov-file#installation

Once done let me know. have tested it locally worked for me.

**Comment by GauriBhandari** [comment]
> LGTM! @GauriBhandari the changes will also take place here : - https://github.com/keploy/docs?tab=readme-ov-file#installation
> 
> Once done let me know. have tested it locally worked for me.

okay i will do the necessary changes and will let you know

**Comment by Sonichigo** [comment]
hi @GauriBhandari you can add issue related to this pr and pr itself here - [.github/kroc'24 at main · keploy/.github](https://github.com/keploy/.github/tree/main/kroc'24) and with the rest of your contributions

**Comment by GauriBhandari** [comment]
> hi @GauriBhandari you can add issue related to this pr and pr itself here - [.github/kroc'24 at main · keploy/.github](https://github.com/keploy/.github/tree/main/kroc'24) and with the rest of your contributions

Sure , will do , Thankyou

**Comment by GauriBhandari** [comment]
Hi @Sonichigo , I've made the necessary changes to include instructions for using npm. It's been about two weeks since I last followed up, and I apologize for the delay. If you find everything in order, could you please consider merging it? Although the KRoC program has ended, I’m still happy to contribute and support the project.
Thank you!

**Comment by Sonichigo** [comment]
Merging the PR! Was updating the rest to make sure those doesn't fail. Thanks for the contribution and participating in the KROC program @GauriBhandari ! We have multiple issues still available please feel free to pick them up :)

**Pull request merged**
