### PR TITLE
Added png images for keploy Java dependencies.

### PR DESCRIPTION
**Pull request by Arpcoder**
# Update documentation for mocking feature of java sdk
- In this issue only adding png for Java dependencies part was left to add.

Closes: #353[keploy/keploy/issues/353]

#### Describe the changes you've made
A new section (supported dependencies) displaying png images for keploy Java dependencies has been added.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas and used java doc.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

**Light-mode**  <b>
image

</b>

 **Dark-mode**  <b>
image

</b>

### CODE REVIEW

**Comment by Arpcoder** [comment]
Please see this mam @nehagup

**Comment by nehagup** [comment]
@Arpcoder can you please post updated screenshot?

**Comment by Arpcoder** [comment]
@nehagup  mam I have already edited my pull request comment with new screenshots. These are screenshots after using svg images.


image


image

**Comment by Arpcoder** [comment]
@nehagup mam, I have added updated screenshots in my PR comment. Here is the updated screenshots -


image

image

**Comment by Arpcoder** [comment]
@nehagup mam I have updated them by keeping aspect ratio constant.

image


image

**Comment by Arpcoder** [comment]
@nehagup mam can you please review it for the last time. I have attached the screenshots in my previous comment.

**Comment by nehagup** [comment]
@Arpcoder the naming of each dependency is still missing. I'm closing this since the documentation for mocking features has been done which was the initial goal of this issue. If you want to add logos of supported dependencies you can follow the same theme as displayed on landing page and open a new PR.
 
Screenshot 2023-05-09 at 3 09 39 AM

**Pull request closed without merging**
