### PR TITLE
added light house ci

### PR DESCRIPTION
**Pull request by Ayush7614**
This PR Contains

Adds a LightHouse CI step to track web performance

### CODE REVIEW

**Comment by Ayush7614** [comment]
Cc @nehagup

**Review by nehagup — APPROVED** [review]

**Comment by Ayush7614** [comment]
cc @nehagup now all checks are done you can review it and merge it

**Comment by Ayush7614** [comment]
cc @nehagup

**Comment by ShivamTyagi12345** [comment]
@Ayush7614  you can sign the DCO by adding the signature locally in the commit message and force pushing. You can click on "Details" of the Failed DCO actions to find the instructions

**Pull request closed without merging**
