### PR TITLE
Update Keploy twitter card image

### LINKED ISSUE #71: [ Documentation request ] Update Keploy twitter card image
# Brief description

As the logo of Keploy has changed, the twitter card in the documentation need to be updated too. Here is the [old](https://github.com/keploy/docs/blob/main/static/img/keploy-logo-twitter-card.png) one. Change the image to a newer one keeping the path same.

#  Your recommended content

You can take reference from [here](https://github.com/keploy/docs/blob/main/static/img/keploy-logo-dark.svg) for the update.

### PR DESCRIPTION
**Pull request by jayeshchoudhary**
# Pull Request Template

## Description

Update Keploy twitter card image

Fixes #71 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by jayeshchoudhary** [comment]
closes #71

**Comment by jayeshchoudhary** [comment]
@SanskritiHarmukh can you please review

**Comment by SanskritiHarmukh** [comment]
LGTM

**Comment by SanskritiHarmukh** [comment]
@jayeshchoudhary Can you please signoff the commit so that the DCO check could be passed?
Write the following 2 commands in the docs terminal and you'll be good to go:
```
git rebase HEAD~1 --signoff
git push --force-with-lease origin main
```

**Comment by jayeshchoudhary** [comment]
@SanskritiHarmukh updated.

**Pull request merged**
