### PR TITLE
docs: add quickstart guide for express prisma sample app

### PR DESCRIPTION
**Pull request by Abbhiishek**
## What has changed?

This PR adds QuickStart guide for https://github.com/keploy/samples-typescript/tree/main/express-postgresql-prisma

This PR Resolves https://github.com/keploy/keploy/issues/2247

## Type of change

Please delete options that are not relevant.

- [x] Documentation update (if none of the other choices apply).

## How Has This Been Tested?

Please run npm run build and npm run serve to check if the changes are working as expected. Please include screenshots of the output of both the commands. Add screenshots/gif of the changes if possible.

image

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by TvisharajiK** [comment]
Hey @Abbhiishek, the supabase flow isn't supported for Keploy right ?

**Comment by Abbhiishek** [comment]
> Hey @Abbhiishek, the supabase flow isn't supported for Keploy right ?

yep! need to remove few lines from the docs

**Comment by Abbhiishek** [comment]
Ready to merge @TvisharajiK 🚀

**Comment by TvisharajiK** [comment]
@Abbhiishek Merged, but look into the Docker as well

**Pull request merged**
