### PR TITLE
docs(readme): add example for elastic-search and redis integration with keploy

### PR DESCRIPTION
**Pull request by iamskp99**
# Pull Request Template

This PR is for these issues: https://github.com/keploy/go-sdk/issues/122 and https://github.com/keploy/go-sdk/issues/131

## Description

Added example for elastic-search integration with keploy.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by littleironical — COMMENTED** [review]
Hi @iamskp99 
I was trying integrate **Elasticsearch** with the [users-profile](https://github.com/keploy/samples-go/tree/main/users-profile) sample application but I'm getting an error which says `undeclared name: domain` 

image

Moreover, for **Redis**, there's no `kredis` package in [github.com/keploy/go-sdk/integrations/kredis](github.com/keploy/go-sdk/integrations/kredis)

**Comment by iamskp99** [comment]
@littleironical the "kredis" integration is not merged into the main branch right now. You can see the changes here : https://github.com/keploy/go-sdk/pull/130/files

For elastic search, the domain variable was used in my sample-gin-elastic app. Here is the PR: https://github.com/keploy/samples-go/pull/15/files. You don't have to use that in your app. It seems that it is adding confusion. I will remove it from the readme.

**Comment by littleironical** [comment]
I've added the `kredis` files in my project and it worked, but for `elastic search` I think you need to update it

**Comment by littleironical** [comment]
`Redis` is working perfectly with **MongoDB** and **Keploy Server**

**Review by littleironical — COMMENTED** [review]
`Redis` is working perfectly with **MongoDB** and **Keploy Server**

**Pull request merged**
