### PR TITLE
changing the blogs link in community section on the home page to point to latest blog site

### PR DESCRIPTION
**Pull request by anshjain16**
## Description

Changed the link of blogs in community section of homepage to point towards latest blog website, previously it was pointing to hashnode blog page
image

previously it looked like - 

image

after changes -
 
image

Fixes # 1886

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?

i tested by clicking on the link option, and it successfully redirects to latest blog website

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by anshjain16** [comment]
Hey @Sonichigo it would be of great help if you could guide me on how to pass these tests, I am a beginner

**Comment by anshjain16** [comment]
Hey @Sonichigo I wrote the commit message according to the given standard, i hope it should work this time

**Comment by anshjain16** [comment]
Hey @Sonichigo can you review this now, i've updated the commit message according to the required standards, i hope it should work now

**Comment by anshjain16** [comment]
Is it fine or do need to do some changes @Sonichigo

**Review by Sonichigo — APPROVED** [review]
LGTM 🚀

**Comment by anshjain16** [comment]
@Sonichigo can this be merged

**Pull request merged**
