### PR TITLE
feat: Stale GitHub Action for PR's older than 50 days

### PR DESCRIPTION
**Pull request by SanjaySinghRajpoot**
# Pull Request Template

## Description

A new GitHub action is added. That will scan all the PRs and mark those PRs which have had no activity for the past 50 days. It will also mark the issues as stale based on the days that passed. 

Fixes #550

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by nehagup — COMMENTED** [review]
@SanjaySinghRajpoot can you please sign the CLA and check linting issue?

**Comment by SanjaySinghRajpoot** [comment]
The error is not relevant to the code. `input: feat: Stale PR github action` It is giving an error because I have used a capital letters in my commit messages.

**Comment by SanjaySinghRajpoot** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SanjaySinghRajpoot** [comment]
> @SanjaySinghRajpoot you can soft reset and commit again following the conventional commit, try `cz c`. Also, please sign the CLA by making the comment.

This is not working. I tried to change the name of the commits but they are not getting updated.

**Comment by nehagup** [comment]
We're currently not able to meet a 30 days TAT for issues and PRs, however, we want to make sure we address all of those at least once. This would make more sense once we have bigger team and better process in place. Thanks for the PR.

**Pull request closed without merging**
