### PR TITLE
Solves GIFs seems grainy/pixelated in dark mode

### PR DESCRIPTION
**Pull request by starvader13**
## Description
The GIF gets grainy and pixelated in the dark mode, the solution is to change the background colour of the image to white.

Fixes https://github.com/keploy/keploy/issues/2020

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue).
- [X] This change requires a documentation update.

## Screenshot

Screenshot from 2024-07-17 19-14-06

Screenshot from 2024-07-17 19-14-38

- [X] My code follows the style guidelines of this project.

### CODE REVIEW

**Comment by starvader13** [comment]
@Swpn0neel Review Required!!

**Comment by Swpn0neel** [comment]
> @Swpn0neel Review Required!!
> 
> Running yarn prettier --write generates a warning. From what I understand, this shouldn't cause any unexpected issues in the future. However, you might want to take a look at it.
> 
> Screenshot from 2024-07-17 19-26-03

If you've already have the setup to prettify Markdown files while saving, in your code editor; it won't be a problem.

But, this is an existing issue, if you want to fix it, you can raise a separate issue for it and I'll count it in under kROC!

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
But this defeats the purpose of Dark Mode. Have you tried altering the GIF by trying to upscale/denoise it?

**Comment by starvader13** [comment]
> But this defeats the purpose of Dark Mode. Have you tried altering the GIF by trying to upscale/denoise it?

I have tried upscaling and denoising it but the graininess was not reducding, that's why I switched over to this solution. It would be great if you could suggest me something ?

**Comment by starvader13** [comment]
> If you've already have the setup to prettify Markdown files while saving, in your code editor; it won't be a problem.
> 
> But, this is an existing issue, if you want to fix it, you can raise a separate issue for it and I'll count it in under kROC!

Yeah as I have gone through the docs, it seems the `jsxBracketSameLine` is deprecated and `bracketSameLine` is what getting used now. I will be creating an issue asap.

**Comment by Swpn0neel** [comment]
> @Swpn0neel I have tried upscaling and denoising it but the graininess was not reducing, that's why I switched over to this solution. It would be great if you could suggest me something.

Ok, then we can go with this solution!

**Comment by starvader13** [comment]
A similar solution could be applied to this one too.

image

**Comment by starvader13** [comment]
@Swpn0neel Any update on this one? I have gone through docs and can not find any other `gif/image` which needs to be refactored.

**Pull request merged**
