### PR TITLE
Improvements in Java SDK Doc

### LINKED ISSUE #55: [ Documentation request ] Improvements in Java SDK Doc
# Brief description
- On navigating to [`How to use the Keploy Java SDK`](https://docs.keploy.io/docs/java/installation) page under  [`Usage`](https://docs.keploy.io/docs/java/installation#usage) -> `Run the testcases` -> `Using command line`, the indentation of steps is irregular. Also, The bullet present in front of 4th point can be removed.

Screenshot from 2022-09-30 23-32-47

- The [Spring Boot + PostgreSQl sample application](https://docs.keploy.io/docs/java/run-your-first-app-tutorial) can be positioned inside Quickstart section.

- In this [part of java sample app documentation](https://docs.keploy.io/docs/java/run-your-first-app-tutorial#testing-using-unit-test-file) the first point is missing and the indentation of rest of the point description and images are disturbed too.

Screenshot from 2022-09-30 23-53-25

#  Your recommended content

Refer to the [java](https://github.com/keploy/docs/tree/main/docs/java) and [quickstart](https://github.com/keploy/docs/tree/main/docs/go/quickstart) folders.

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>

# Pull Request Template

## Description
indentation fix

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #55 

## Type of change

- [x] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh @Manoj0Marmat doc formatting fix

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh @nehagup please review it

**Comment by SanskritiHarmukh** [comment]
LGTM!

**Comment by nehagup** [comment]
@gouravkrosx can you please review this PR too?

**Pull request merged**
