### PR TITLE
Fixes faulty URLs

### PR DESCRIPTION
**Pull request by jailbreakerVC**
# Pull Request Template

## Description

Fixes faulty URLs 

Fixes keploy/keploy#973

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).

## How Has This Been Tested?

No tests as of now.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by jailbreakerVC** [comment]
@nehagup Hi, is the lockfile supposed to be committed?

**Review by nehagup — CHANGES_REQUESTED** [review]
Thanks for the PR @jailbreakerVC ! 

There's a breaking link on http://localhost:3000/docs/1.0.0/concepts/what-are-keploy-features/ - check the last link of the page with "[contribution guide](http://localhost:3000/devtools/sdk-contrib-guide)."

**Comment by nehagup** [comment]
> @nehagup Hi, is the lockfile supposed to be committed?

If there's no package change then it's preferred not to commit the lock file.

**Comment by jailbreakerVC** [comment]
Alright, I will look into it, thanks. Should I do anything about the Lint Codebase check that's failing? I'll take of it next time.

**Comment by nehagup** [comment]
> Thanks, @nehagup. I will look into it. Should I do anything about the Lint Codebase check that's failing? I'll take of it next time.

You can give your best shot to resolve it, otherwise I'll merge

**Review by nehagup — APPROVED** [review]

**Pull request merged**
