### PR TITLE
add: hover over Supports cards

### PR DESCRIPTION
**Pull request by Aman172003**
This change resolves [ #2091](https://github.com/keploy/keploy/issues/2091) by adding hover effect to supports cards.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?
Changes were tested locally to ensure functionality.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Aman172003** [comment]
@Sonichigo could you please review the PR.

**Comment by Sonichigo** [comment]
hey @Aman172003 ! How did the experienced change from current one on keploy.io/docs ?

https://github.com/user-attachments/assets/9cabd53f-6d53-48b2-90af-82d08a25a09f

**Comment by Sonichigo** [comment]
@Aman172003 are you working on this?

**Comment by Aman172003** [comment]
@Sonichigo 

https://github.com/user-attachments/assets/72ec67e5-eb6d-41ff-a78c-ab2871921a0b

Initially both of the cards were not able to show any transition

**Review by Sonichigo — COMMENTED** [review]
Can you also add something for the darkmode as well. In Light Mode it looked good to me.

image

**Comment by Aman172003** [comment]
@Sonichigo could you please close this pr, i want to raise a new pr with this issue

**Pull request closed without merging**
