### PR TITLE
Add glossary

### PR DESCRIPTION
**Pull request by developer-diganta**
# Pull Request Template

## Description

Added a glossary page

### CODE REVIEW

**Comment by Sonichigo** [comment]
Here are few suggestions:-
- Grid view would be better than list view
- The Letter with missing Terminology would be disabled by default
- Box background should be not there by default, rather once the user clicks on the letter then it should be visible.

**Comment by Sonichigo** [comment]
Also sign DCO and check the Lint once-

**Comment by Sonichigo** [comment]
Screenshot 2023-07-03 at 12 44 30 PM

LGTM @nehagup

**Review by nehagup — COMMENTED** [review]
@developer-diganta Needs fix on duplicate pages, also the content needs improvement. @Sonichigo please help.

**Pull request merged**
