### PR TITLE
Added more topics in Sidebar

### LINKED ISSUE #29: [Documentation request]: Adding more topics in the Sidebar
# Brief description

We have asked a few developers to go through our documentation and find the barriers they are facing while understanding Keploy. One of them found it difficult to navigate to different pages!

#  Recommendation

To make the documentation easy for navigation for the developers, we can **increase the number of topics that are available in the sidebar**. Currently, we have to go to the navbar to check for the topics available in the documentation.

### Something like this:
image

### PR DESCRIPTION
**Pull request by littleironical**
## Description

Added all the topics and subtopics that were available on the navbar to the sidebar.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] This change requires a documentation update.

## Additional Context

image

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by littleironical** [comment]
@nehagup please check this out

**Comment by nehagup** [comment]
@littleironical the bars on the top needs to be removed and the sidebar also needs to be shown on the front page since the whole point of adding these sections to sidebar is easy navigation.

**Review by nehagup — CHANGES_REQUESTED** [review]
refine according to navigation UX

**Comment by littleironical** [comment]
As discussed earlier, I did some edits in the website and also fixed some bugs that my previous commits had. Do check them out.

**Pull request merged**
