### PR TITLE
fix : added mongodb support images

### PR DESCRIPTION
**Pull request by Swpn0neel**
# Pull Request Template

## Description

Added the images for MongoDB support

Fixes [#1221](https://github.com/keploy/keploy/issues/1221)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] This change requires a documentation update.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Arindam200 — CHANGES_REQUESTED** [review]
This PR is incomplete. You have just added the images

Please add the paths to the images.

**Comment by Swpn0neel** [comment]
> @Swpn0neel This PR is incomplete. You have just added the images
> 
> Please add the paths to the images.

Hey @Arindam200, I've implemented the requested changes, kindly check it now!!

**Comment by Swpn0neel** [comment]
> @Swpn0neel This PR is incomplete. You have just added the images
> 
> Please add the paths to the images.

Hey @Arindam200 , I've implemented the requested changes, kindly check it now!! <br>
image

**Review by Arindam200 — APPROVED** [review]

**Review by Shashwat79802 — APPROVED** [review]

**Comment by Shashwat79802** [comment]
Good to go

**Review by Sonichigo — APPROVED** [review]
LGTM

**Pull request merged**
