### PR TITLE
fix: typo for no of modes

### PR DESCRIPTION
**Pull request by jaiakash**
## Description
In the docs, it was mentioned that Keploy has 3 modes, but it has only 2 as of now, `record` and `test`.

Fixes https://github.com/keploy/keploy/issues/2139

## Type of change

- [x] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by jaiakash** [comment]
@Sonichigo I have added the typo fix. 

https://keploy.io/docs/keploy-explained/contribution-guide/#now-lets-try-running-keploy
Also, I think the command to run Keploy is also old, ie `go run -exec "sudo -E env 'PATH=$PATH'" -tags=viper_bind_struct main.go test -c "path/to/go/binary/of/application" --delay 10`

We can update the docs with the installation link and update the commands to run `Keploy` cmd directly.
Lmk, what do you think?

**Comment by Sonichigo** [comment]
> @Sonichigo I have added the typo fix.
> 
> https://keploy.io/docs/keploy-explained/contribution-guide/#now-lets-try-running-keploy Also, I think the command to run Keploy is also old, ie `go run -exec "sudo -E env 'PATH=$PATH'" -tags=viper_bind_struct main.go test -c "path/to/go/binary/of/application" --delay 10`
> 
> We can update the docs with the installation link and update the commands to run `Keploy` cmd directly. Lmk, what do you think?

I don't think it would be necessary since the commands mentioned in the contribution guides are for local development and testing of keploy.

**Comment by jaiakash** [comment]
Sure, then this PR is good to go.

**Comment by jaiakash** [comment]
Also is it possible to add KRoC tag to this PR?

**Comment by Sonichigo** [comment]
> Also is it possible to add KRoC tag to this PR?

Hi sure! you can add 1 point in the leaderboard for this on https://github.com/keploy/.github/tree/main/kroc'24

**Pull request merged**
