### PR TITLE
added docs for spring-boot-mongo

### PR DESCRIPTION
**Pull request by officialasishkumar**
# Pull Request Template

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes [#1175](https://github.com/keploy/keploy/issues/1175)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by officialasishkumar** [comment]
@Shashwat79802 @Sonichigo Please take a look

**Review by Arindam200 — APPROVED** [review]

**Comment by Shashwat79802** [comment]
@officialasishkumar please modify this documentation according to the docs structure we're following for most of our documentation. You can see a common way of creating the docs in the Python and Golang dropdown in the docs website sidebar.

Here's something for your reference - https://keploy.io/docs/quickstart/samples-mux/
https://keploy.io/docs/quickstart/samples-django/

**Comment by nehagup** [comment]
@officialasishkumar are you still working on this?

**Comment by officialasishkumar** [comment]
> @officialasishkumar are you still working on this?

@nehagup 
Yeah. I have my exams going on. Will update with the suggested changes soon!

**Comment by officialasishkumar** [comment]
> @officialasishkumar please modify this documentation according to the docs structure we're following for most of our documentation. You can see a common way of creating the docs in the Python and Golang dropdown in the docs website sidebar.
> 
> Here's something for your reference - https://keploy.io/docs/quickstart/samples-mux/ https://keploy.io/docs/quickstart/samples-django/

Hey @Shashwat79802, Can you please tell me all the steps you used to run spring-boot-mongo using docker?

**Review by Arindam200 — APPROVED** [review]

**Comment by Sonichigo** [comment]
hey @officialasishkumar can you please resolve the conflicts ?

**Comment by officialasishkumar** [comment]
done @Sonichigo

**Pull request merged**
