### PR TITLE
Fix : alignment of keploy logo in nav bar

### LINKED ISSUE #75: [ Documentation request ] Fix alignment of keploy logo in nav bar
# Brief description

On visiting [Documentation website](https://docs.keploy.io/), you can see that at the navigation bar, keploy logo is not aligned with rest of the nav bar items. So, fix the alignment such that all the items appears in a line.

Screenshot from 2022-10-06 23-42-28

#  Your recommended content

You can refer to [this](https://github.com/keploy/docs/blob/1cfe23a4db27ccbf456bd87231b3712432623470/docusaurus.config.js) file.

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
# Pull Request Template

## Description
fixing bottom margin of logo

Fixes #75
Screenshot 2022-10-07 at 9 47 06 AM

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] I have added corresponding tests.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
closes #75

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh mam logo margin fix

**Comment by nehagup** [comment]
@Manoj0Marmat can you please sign the DCO?

**Comment by Manoj0Marmat** [comment]
@nehagup mam need help i'm beginner can you please share steps to do that

**Comment by SanskritiHarmukh** [comment]
@Manoj0Marmat 
Write the following 2 commands in the docs terminal to sign off the commit:
```
git rebase HEAD~1 --signoff
git push --force-with-lease origin main
```

Reopening the PR as the changes are appropriate.

**Comment by Manoj0Marmat** [comment]
@SanskritiHarmukh sorry i'm doing this first time i raise another pr and signed DCO please review that one

**Comment by ShivamTyagi12345** [comment]
Hey @Sonichigo  Removing this label as the PR is Closed and not merged

**Pull request closed without merging**
