### PR TITLE
Added the code blocks and code Highlighting

### PR DESCRIPTION
**Pull request by Aditya-eddy**
# Pull Request Template
Fixes the [issue](https://github.com/keploy/keploy/issues/1530) and also the CodeHighlighting.
## Description

1. Did'nt Render the MDX component because the content was not wrapped around MDXcontent.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] This change requires a documentation update.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added corresponding tests.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have finally added the copy to clipboard button as well as the syntax Highlighting. Will be waiting on review. Thanks!! I'll Attach the screenshots with it.
Screenshot from 2024-02-14 10-01-19

**Review by nehagup — CHANGES_REQUESTED** [review]
@Aditya-eddy the changes looks great! Just that some of the code blocks, for example - /docs/server/windows/installation/#one-click-install-keploy are not appearing with syntax highlighting. 

Also there are build errors - 

```

[ERROR] Unable to build website for locale en.
[ERROR] Error: Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /docs/1.0.0/concepts/what-is-keploy-sdk/:
   -> linking to /docs/go/installation/

- On source page path = /docs/1.0.0/devtools/introduction/:
   -> linking to /docs/devtools/server-contrib-guide/
   -> linking to /docs/devtools/sdk-contrib-guide/
   -> linking to /docs/devtools/ui-contrib-guide/
   -> linking to /docs/devtools/docs-contrib-guide/

- On source page path = /docs/1.0.0/go/quickstart/gin-mongo/:
   -> linking to /docs/go/quickstart/gin-mongo/#testing-using-unit-test-file (resolved as: /docs/go/quickstart/gin-mongo/)
   -> linking to /docs/go/quickstart/gin-mongo/#testing-using-keploy_mode-env-variable (resolved as: /docs/go/quickstart/gin-mongo/)

- On source page path = /docs/1.0.0/java/quickstart/:
   -> linking to /docs/java/quickstart/spring-sql/

- On source page path = /docs/1.0.0/keploy-explained/introduction/:
   -> linking to /docs/go/installation/

- On source page path = /docs/1.0.0/server/sdk-installation/:
   -> linking to /docs/go/installation/

- On source page path = /docs/concepts/:
   -> linking to /docs/concepts/what-is-keploy-sdk/

- On source page path = /docs/dependencies/:
   -> linking to /docs/dependencies/postgresql/

    at throwError (/Users/neha/open-source/docs/node_modules/@docusaurus/logger/lib/index.js:76:11)
    at handleBrokenLinks (/Users/neha/open-source/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:153:47)
    at async buildLocale (/Users/neha/open-source/docs/node_modules/@docusaurus/core/lib/commands/build.js:186:5)
    at async tryToBuildLocale (/Users/neha/open-source/docs/node_modules/@docusaurus/core/lib/commands/build.js:41:20)
    at async mapAsyncSequential (/Users/neha/open-source/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/Users/neha/open-source/docs/node_modules/@docusaurus/core/lib/commands/build.js:76:21)
```

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have pushed the changes and the build is working fine. Can you confirm it and also any feedback would be appreciated. Thanks!!

**Comment by nehagup** [comment]
Thanks for the PR! I made a few changes and closed it in https://github.com/keploy/docs/pull/333

**Pull request closed without merging**
