### PR TITLE
[docs]: added example for handling nested JSON fields

### PR DESCRIPTION
**Pull request by GauriBhandari**
# Pull Request Template

## Description

This PR adds an example for handling deeply nested JSON fields in the Keploy configuration file. The added example illustrates how to specify paths for nested fields such as tokens in the global noise configuration.

Changes Made
Added an example JSON response demonstrating deeply nested fields.
Provided YAML configuration showing how to specify paths for nested fields in the global noise section.
Included detailed comments to help users understand the configuration.

Fixes https://github.com/keploy/keploy/issues/1892

## Type of change
Documentation Enhancement  

- [x] This change requires a documentation update.

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by GauriBhandari** [comment]
@Swpn0neel could you please help , what am i suppose to do now , i didn't get why i have again failed the DCO check , i have configure Docusaurus in my system as you instructed yesterday

**Comment by GauriBhandari** [comment]
The issue has been solved @Swpn0neel , could you kindly review the pull request and merge it if everything looks good?

**Review by Swpn0neel — APPROVED** [review]
LGTM!

**Comment by GauriBhandari** [comment]
Thank you for reviewing the pull request @Swpn0neel . Since you mentioned that it looks good to you, could you please proceed with merging it?

**Review by khareyash05 — APPROVED** [review]
LGTM!

**Comment by khareyash05** [comment]
Requesting @Sonichigo for approval

**Pull request merged**
